name: portafolio
description: "My portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  theme_tailor_annotation: ^2.0.2
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  grouped_list: ^5.1.2
  permission_handler: ^11.1.0
  styled_text: ^8.1.0
  flutter_animated_dialog: ^2.0.1
  dropdown_button2: ^2.3.9
  json_annotation: ^4.7.0
  intl: ^0.18.0
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  mocktail: ^1.0.0
  provider: ^6.0.5
  riverpod: ^2.4.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  bloc_test: ^9.1.4
  timeline_tile: ^2.0.0
  dio: ^5.3.3
  open_file: ^3.3.2
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.14
  hooks_riverpod: ^2.4.5
  url_strategy: ^0.2.0
  state_notifier: ^1.0.0
  text_divider: ^1.0.0
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.2
  icons_plus: ^5.0.0
  country_icons: ^2.0.2
  sprung: ^3.0.1
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  rxdart: ^0.27.7
  flutter_emoji: ^2.5.1
  go_router: ^13.0.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  mask_text_input_formatter: ^2.7.0
  email_validator: ^2.1.17
  sidebarx: ^0.16.2
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  theme_tailor: ^2.0.2
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/pictures/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito/Nunito-Italic-VariableFont_wght.ttf
        - asset: assets/font/Nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/font/Nunito/static/Nunito-Black.ttf
        - asset: assets/font/Nunito/static/Nunito-BlackItalic.ttf
        - asset: assets/font/Nunito/static/Nunito-Bold.ttf
        - asset: assets/font/Nunito/static/Nunito-BoldItalic.ttf
        - asset: assets/font/Nunito/static/Nunito-ExtraBold.ttf
        - asset: assets/font/Nunito/static/Nunito-ExtraBoldItalic.ttf
        - asset: assets/font/Nunito/static/Nunito-ExtraLight.ttf
        - asset: assets/font/Nunito/static/Nunito-ExtraLightItalic.ttf
        - asset: assets/font/Nunito/static/Nunito-Italic.ttf
        - asset: assets/font/Nunito/static/Nunito-Light.ttf
        - asset: assets/font/Nunito/static/Nunito-LightItalic.ttf
        - asset: assets/font/Nunito/static/Nunito-Medium.ttf
        - asset: assets/font/Nunito/static/Nunito-MediumItalic.ttf
        - asset: assets/font/Nunito/static/Nunito-Regular.ttf
        - asset: assets/font/Nunito/static/Nunito-SemiBold.ttf
        - asset: assets/font/Nunito/static/Nunito-SemiBoldItalic.ttf

    - family: Inter
      fonts:
        - asset: assets/font/inter/Inter-Bold.ttf
        - asset: assets/font/inter/Inter-ExtraBold.ttf
        - asset: assets/font/inter/Inter-ExtraLight.ttf
        - asset: assets/font/inter/Inter-Light.ttf
        - asset: assets/font/inter/Inter-Medium.ttf
        - asset: assets/font/inter/Inter-Regular.ttf
        - asset: assets/font/inter/Inter-SemiBold.ttf
        - asset: assets/font/inter/Inter-Thin.ttf

    - family: Noto Serif Display
      fonts:
        - asset: assets/font/noto/NotoSerifDisplay-Bold.ttf
        - asset: assets/font/noto/NotoSerifDisplay-ExtraBoldItalic.ttf
        - asset: assets/font/noto/NotoSerifDisplay-Italic.ttf
        - asset: assets/font/noto/NotoSerifDisplay-Medium.ttf
        - asset: assets/font/noto/NotoSerifDisplay-Regular.ttf
        - asset: assets/font/noto/NotoSerifDisplay-SemiBold.ttf

    - family: Vibes
      fonts:
        - asset: assets/font/vibes/GreatVibes-Regular.ttf

    - family: Kalam
      fonts:
        - asset: assets/font/kalam/Kalam-Bold.ttf
        - asset: assets/font/kalam/Kalam-Light.ttf
        - asset: assets/font/kalam/Kalam-Regular.ttf

    - family: Shadow
      fonts:
        - asset: assets/font/shadow/ShadowsIntoLight-Regular.ttf